language:
   - rust

script:
    - cargo build --release
    # Run unit tests:
    - cargo test --lib --features=tst_utils -- --test-threads=5
    # Run integration tests:
    - cargo test --test learn_line --features=tst_utils -- --test-threads=5

branches:
  only:
    - master

notifications:
email: false
